apiVersion: v1
kind: PersistentVolume 
metadata:
  name: host-pv
spec:
  capacity:
    storage: "500Mi"
  volumeMode: Filesystem
  storageClassName: hostpath
  accessModes: 
    - ReadWriteOnce
  hostPath: 
    path: /data
    type: DirectoryOrCreate